name: Release

on: [push, pull_request]

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2      
      
      - name: Install dependencies
        run: v install markdown
      
      - name: Create output dir
        run: mkdir build
      
      - name: Build ${{ github.event.repository.name }}
        run: v -enable-globals -prod . -o build/v2Lib
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: ${{ github.run_number }}
          files: build/*
