name: Release

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2      
      
      - name: Install dependencies
        run: v install markdown
      
      - name: Build ${{ github.event.repository.name }}
        run: v -enable-globals -prod . -o build v2Lib
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          prerelease: true
          files: build/*
